version: "3"
services:
  event-service:
    build: .
    image: event-service
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "5025:5025"
    entrypoint:
      - /opt/venv/bin/python
      - -m
      - gunicorn
      - eventservice.entrypoints.wsgi:app
    environment:
      GUNICORN_CMD_ARGS: -b 0.0.0.0:5025 --workers 1 --threads 4 --log-level info --timeout 600
  kafka:
    image: confluentinc/cp-kafka:6.2.6
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.6
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.6
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1